# -*- coding: utf-8 -*-
"""T. Dheeraj Reddy (AP24110011473).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_oqxfp3ykcb2zQHeiR5fX0R1qSHTKyX8

# NumPy Hands-on Lab: From Arrays to Image Analysis

## Student Practice Notebook

**Name:** T.Dheeraj Reddy

**Register Number:** AP24110011473

**Date:** 07/08/2026

## Learning Objectives

After completing this lab, you will be able to:

- Create and manipulate NumPy arrays
- Understand array properties and dimensions
- Perform indexing and slicing
- Apply mathematical operations
- Understand and explain broadcasting
- Analyze images using NumPy arrays
- Perform basic image transformations
- Explain *why* NumPy is used in real ML/Data Science pipelines, not just *how*

### How to use this notebook
- **Demonstration** cells: run them, read the output, understand it.
- **Practice** cells: write your own code — don't copy the demo verbatim.
- **Predict-then-run**: before running some cells, you'll be asked to *predict* the output first. Write your prediction in the markdown cell, then run and compare.
- **Reflection**: short written answers, in your own words.

## Part 1: Introduction to NumPy

NumPy (Numerical Python) is a Python library used for efficient numerical computation.

**Why not just use Python lists?** Python lists store objects with overhead per element and loop in pure Python. NumPy arrays store raw numbers in contiguous memory and use compiled C code for operations — this is called **vectorization**. That's why NumPy is used everywhere in:

- Data Science (pandas is built on NumPy)
- Machine Learning (feeding data into models as arrays/tensors)
- Image Processing (an image *is* a NumPy array)
- Scientific Computing

Let's actually *see* the speed difference before we take it on faith.
"""

import numpy as np
import matplotlib.pyplot as plt

print("NumPy is ready!")

"""### Demonstration: Loops vs. Vectorization (the "why" behind NumPy)

Below we add 1 to a million numbers two ways: a plain Python loop, and a NumPy array operation.
Run this cell and look at the timing output.

"""

import time

n = 1_000_000
python_list = list(range(n))
numpy_array = np.arange(n)

start = time.time()
result_list = [x + 1 for x in python_list]
loop_time = time.time() - start

start = time.time()
result_array = numpy_array + 1
vector_time = time.time() - start

print(f"Python loop time : {loop_time:.5f} seconds")
print(f"NumPy vector time: {vector_time:.5f} seconds")
print(f"NumPy was about {loop_time/vector_time:.0f}x faster")

"""**Reflection (write your answer):** Based on the timing above, in your own words, why is NumPy faster than a Python loop for this kind of operation?

*Your answer:*NumPy is faster since it consistes elements in contiguous memory and has a C complied code while helps it much faster to compute the operation. While List has the references of objects and while performing the operation it must check the element type and necessary  conditions and then must evaluate and sends back results which take much time . So, that why we use NumPys over Lists

## Part 2: Creating NumPy Arrays

### Demonstration
"""

arr = np.array([10,20,30,40,50])
arr

"""### Student Practice

Create an array containing:

5, 10, 15, 20, 25

Write your code below (do not just copy the demo — change the numbers yourself):

"""

# Write your answer here
import numpy as np

array=np.array([25,50,75,100])
array

"""## Part 3: Array Properties

Important properties:

- `ndim` : Number of dimensions
- `shape` : Size of each dimension
- `size` : Total number of elements
- `dtype` : Data type

**Predict first:** for the array `arr` from Part 2, what do you *expect* `ndim`, `shape`, `size`, and `dtype` to be? Write your guess below before running the next cell.

*Your prediction:* 1,(4,),4,Integer


"""

import numpy as np

arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(arr)
arr

print(arr.shape)
print(arr.ndim, arr.shape, arr.size, arr.dtype)
arr

"""### Observation

Was your prediction correct? If not, what did you get wrong and why?

Dimension:

Shape:

Size:

Data Type:

## Part 4: Special Arrays

These are commonly used to initialize data — for example, `zeros` is often used to create an empty "canvas" array before filling in real values (you'll see this again in the image section).
"""

np.zeros((3,3))

np.ones((4,4))

np.eye(3)

"""### Student Practice

Create a `5x5` array of all zeros, and a `2x6` array of all ones. Write both below.

"""

# Write your answer here
import numpy as np

arr=np.zeros((5,5))
b=np.ones((2,6))
print(arr)

print(b)

"""## Part 5: Sequence Generation"""

np.arange(0,50,5)

np.linspace(0,100,10)

"""### Student Practice

`np.arange` and `np.linspace` both generate sequences but work differently.

1. Use `np.arange` to generate even numbers from 2 to 20.
2. Use `np.linspace` to generate 5 evenly spaced numbers between 0 and 1.
3. In one sentence, write the difference between `arange` (step-based) and `linspace` (count-based).

"""

# Write your answer here
import numpy as np
arr=np.arange(2,20,2)
arr

"""## Part 6: Random Numbers"""

np.random.rand(5)

np.random.randint(1,100,10)

"""## Part 7: Reshaping Arrays

Reshape changes the *structure* of an array without changing the data.

**Rule: the total number of elements must stay the same.** `3x4 = 12` elements, so you can reshape into any combination of dimensions that multiplies to 12 (e.g. `2x6`, `4x3`, `1x12`, `12x1`).

"""

a = np.arange(12)
a.reshape(3,4)

"""### Student Practice — valid shapes

Try reshaping `a` into these shapes. Write each as a separate line:
- 2 x 6
- 4 x 3
- 6 x 2

"""

# Practice here

import numpy as np
a=np.arange(12)
b=a.reshape(2,6)
print(b)
c=a.reshape(4,3)
print(c)
d=a.reshape(6,2)
print(d)

"""### Student Practice — break it on purpose

Now try `a.reshape(5,3)`. This should throw an error because 5 × 3 = 15 ≠ 12.

Run it, read the error message, then answer: **why did it fail, and what rule does it confirm about reshape?**

*Your answer:*

"""

# Try the invalid reshape here and observe the error

import numpy as np
a=np.arange(12)
b=a.reshape(5,3)
print(b)

cannot reshape array of size 12 into shape (5,3) since the size of array is 12 and the reshape size must be of multiple of total elements

"""## Part 8: Indexing and Slicing"""

matrix = np.arange(1,10).reshape(3,3)
matrix

# Extract first row
matrix[0]

# Extract first column
matrix[:,0]

"""### Student Practice

Using `matrix` above, write code to extract:
1. The last row
2. The last column
3. The single element in the middle (row 1, column 1)
4. The bottom-right 2x2 sub-matrix

"""

# Write your answer here


import numpy as np
matrix=np.arange(1,17).reshape(2,8)
b=matrix[:]

"""
## Part 9: Mathematical Operations"""

import numpy as np



marks = np.array([60,70,80,90])

marks + 5

marks * 2

"""### Student Practice

A student scored `marks = [55, 62, 48, 91, 73]` but every question was later found to be worth 1 extra bonus mark, and then the whole test was scaled to be out of 150 (currently out of 100, so multiply by 1.5).

Write the NumPy code to: (1) add the bonus mark to every score, then (2) scale to out of 150.

"""

# Write your answer here

import numpy as np
marks = np.array([55, 62, 48, 91, 73])

marks=marks + 1
marks=marks*1.5

"""## Part 10: Broadcasting

Broadcasting lets NumPy perform operations between arrays of **different shapes**, without writing an explicit loop, by "stretching" the smaller array to match the larger one — as long as their shapes are compatible.

**The basic rule:** starting from the trailing (rightmost) dimension, two dimensions are compatible if they're equal, or one of them is 1. NumPy then virtually repeats the size-1 dimension to match.

You already used broadcasting in Part 9 (`marks + 5`) — a single number (shape `()`) was broadcast across the whole array. Here's a less obvious example: a 1D array broadcast across a 2D array.

"""

import numpy as np

salary = np.array([30000,40000,50000])

salary * 1.10

# A less obvious broadcasting example: adding a 1D array to every row of a 2D array
grid = np.ones((3,3))       # shape (3,3)
row_bonus = np.array([1,2,3])  # shape (3,)

grid + row_bonus

"""### Student Practice — predict then check

Before running the next cell, predict the output shape and values on paper.

`np.array([[1],[2],[3]]) + np.array([10,20,30])`

(Hint: one array has shape `(3,1)`, the other `(3,)`. Think about how each dimension aligns.)

*Your prediction:* Shape will be 3*3 values : [11 21 31]
                                              [12 22 32]
                                              [13 23 33]

"""

# Run this after writing your prediction above, and compare
np.array([[1],[2],[3]]) + np.array([10,20,30])

"""**Reflection:** In your own words, explain broadcasting with an example of your own (not one from this notebook).

*Your answer:* Broadcasting means NumPy automatically expands a smaller array to match a larger array's shape so that operations can be performed.


import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)

## Part 11: Filtering Data (Boolean Indexing)
"""

marks = np.array([45,67,89,32,90,55])

marks[marks > 60]

"""### Student Practice

Using the `marks` array above:
1. Extract all marks that are failing (below 40).
2. Count how many students scored above 80 (hint: `.sum()` on a boolean array counts `True` values).
3. Replace all failing marks with 0 using `np.where`.

"""

# Write your answer here

import numpy as np
marks = np.array([45,67,89,32,90,55])
a=marks[marks<40]
b=(marks>80).sum()
c=np.where(marks<40,0,marks)

print(a)
print(b)
print(c)

"""## Part 12: Joining Arrays"""

a=np.array([1,2,3])
b=np.array([4,5,6])

np.concatenate([a,b])

"""## Part 13: Splitting Arrays"""

x=np.arange(12)

np.split(x,3)

"""### Student Practice

1. Split `x` into 4 equal parts instead of 3.
2. Try `np.split(x, 5)` — this should fail. Read the error and explain in one sentence why splitting into 5 doesn't work for 12 elements.

"""

# Write your answer here
import numpy as np
x=np.arange(12)

a=np.split(x,4)
b=np.split(x,5)
print(a)
print(b)

"""# Part 14: Image Analysis Using NumPy

## Why this matters for ML

A digital image **is** a NumPy array — this is exactly the data format used to feed images into computer vision models (e.g. CNNs). Every preprocessing step you do below (resizing, cropping, normalizing pixel values, flipping for data augmentation) is a real step used in production ML image pipelines, not just a classroom exercise.

## Image Shape Guidelines

A colour image is represented as:

`(height, width, channels)`

Example: `512 x 512 x 3` means:
- Height = 512 pixels
- Width = 512 pixels
- RGB colour channels = 3

**Avoid very large images** — a `4000 x 4000 x 3` image has 48 million individual pixel values. That's a lot to process and display.

Recommended:
- Practice: 300x300 pixels
- Processing: 512x512 pixels

"""

from google.colab import files

uploaded = files.upload()

# The 'uploaded' variable is a dictionary: {filename: file_bytes}
# This line grabs the filename automatically instead of you typing it by hand
import numpy as np

image_filename = list(uploaded.keys())[0]
print("Uploaded file:", image_filename)

"""> **Note:** the cell above only works in Google Colab. If you're running this notebook locally (Jupyter/VS Code), skip it and instead set `image_path = "your_local_file.jpg"` directly in the next cell.


from google.colab import files

uploaded = files.upload()

image_path = "cat.jpg"

print("Image uploaded:", image_path)

"""

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

image_filename = "Screenshot 2026-08-13 154054.png"

img = Image.open(image_filename)
img_array = np.array(img)

print(img_array.shape)

"""## Image Display

**Do not print the complete image array** (it's thousands of numbers and unreadable). Instead:
- Use `image.shape` to check dimensions
- Use `plt.imshow(...)` to *see* the image visually

### Student Practice
Display your uploaded image using `plt.imshow()` and turn off the axis with `plt.axis("off")`.

import matplotlib.pyplot as plt

plt.imshow(img_array)
plt.axis("off")
plt.show()
"""

# Write your code here to display img_array


import matplotlib.pyplot as plt

plt.imshow(img_array)
plt.axis("off")
plt.show()

"""## Image Cropping

### Student Practice
Crop the **center 200x200 region** of your image (not a random corner — think about how to calculate the center offset from `img_array.shape`), store it in a variable called `crop`, and display it.


import matplotlib.pyplot as plt

height, width = img_array.shape[:2]

start_y = (height - 200) // 2
start_x = (width - 200) // 2

crop = img_array[start_y:start_y+200, start_x:start_x+200]

plt.imshow(crop)
plt.axis("off")
plt.show()
"""

# Write your cropping code here
import matplotlib.pyplot as plt

height, width = img_array.shape[:2]

start_y = (height - 200) // 2
start_x = (width - 200) // 2

crop = img_array[start_y:start_y+200, start_x:start_x+200]

plt.imshow(crop)
plt.axis("off")
plt.show()

"""### Quick demo: showing multiple images side by side

You'll want to display more than one image at once in the tasks below (e.g. two flipped versions, or three RGB channels). `plt.subplots()` lets you do this in a grid. Study this small example, then reuse the pattern.

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2)

axes[0].imshow(img_array)
axes[0].axis("off")

axes[1].imshow(crop)
axes[1].axis("off")

plt.show()

"""

# Demo: showing 2 plots side by side using plt.subplots
fig, axes = plt.subplots(1, 2, figsize=(8,4))

axes[0].imshow(img_array)
axes[0].set_title("Original")
axes[0].axis("off")

axes[1].imshow(img_array)
axes[1].set_title("Original (again, just for demo)")
axes[1].axis("off")

plt.show()

"""## Image Flipping

### Student Practice
Produce and display both a vertical flip and a horizontal flip of your image using slicing (`[::-1]`), without using any built-in flip function.

import matplotlib.pyplot as plt

# Vertical flip (top ↔ bottom)
vertical_flip = img_array[::-1, :]

# Horizontal flip (left ↔ right)
horizontal_flip = img_array[:, ::-1]

# Display both
fig, axes = plt.subplots(1, 2)

axes[0].imshow(vertical_flip)
axes[0].axis("off")
axes[0].set_title("Vertical Flip")

axes[1].imshow(horizontal_flip)
axes[1].axis("off")
axes[1].set_title("Horizontal Flip")

plt.show()

"""

# Write your flipping code here


import matplotlib.pyplot as plt

# Vertical flip (top ↔ bottom)
vertical_flip = img_array[::-1, :]

# Horizontal flip (left ↔ right)
horizontal_flip = img_array[:, ::-1]

# Display both
fig, axes = plt.subplots(1, 2)

axes[0].imshow(vertical_flip)
axes[0].axis("off")
axes[0].set_title("Vertical Flip")

axes[1].imshow(horizontal_flip)
axes[1].axis("off")
axes[1].set_title("Horizontal Flip")

plt.show()

"""## RGB Channel Analysis

RGB channels:

- 0 - Red
- 1 - Green
- 2 - Blue

### Student Practice
Extract the red, green, and blue channels separately, and display each one using `plt.imshow(channel, cmap="gray")` so you can see which areas of the image are strongest in each color.

import matplotlib.pyplot as plt

# Extract RGB channels
red = img_array[:, :, 0]
green = img_array[:, :, 1]
blue = img_array[:, :, 2]

# Display the three channels
fig, axes = plt.subplots(1, 3, figsize=(12, 4))

axes[0].imshow(red, cmap="gray")
axes[0].set_title("Red Channel")
axes[0].axis("off")

axes[1].imshow(green, cmap="gray")
axes[1].set_title("Green Channel")
axes[1].axis("off")

axes[2].imshow(blue, cmap="gray")
axes[2].set_title("Blue Channel")
axes[2].axis("off")

plt.show()
"""

# Write your RGB channel code here

import matplotlib.pyplot as plt

# Extract RGB channels
red = img_array[:, :, 0]
green = img_array[:, :, 1]
blue = img_array[:, :, 2]

# Display the three channels
fig, axes = plt.subplots(1, 3, figsize=(12, 4))

axes[0].imshow(red, cmap="gray")
axes[0].set_title("Red Channel")
axes[0].axis("off")

axes[1].imshow(green, cmap="gray")
axes[1].set_title("Green Channel")
axes[1].axis("off")

axes[2].imshow(blue, cmap="gray")
axes[2].set_title("Blue Channel")
axes[2].axis("off")

plt.show()

"""## Brightness Analysis

### Student Practice
Calculate the average brightness of your image using `np.mean()`. Then calculate the average brightness of just the red channel, just the green channel, and just the blue channel. Which channel is brightest? Write your answer below the code.

import numpy as np

# Average brightness of the whole image
overall_brightness = np.mean(img_array)

# Average brightness of each channel
red_brightness = np.mean(red)
green_brightness = np.mean(green)
blue_brightness = np.mean(blue)

print("Overall brightness:", overall_brightness)
print("Red brightness:", red_brightness)
print("Green brightness:", green_brightness)
print("Blue brightness:", blue_brightness)

"""

# Write your brightness code here

import numpy as np

# Average brightness of the whole image
overall_brightness = np.mean(img_array)

# Average brightness of each channel
red_brightness = np.mean(red)
green_brightness = np.mean(green)
blue_brightness = np.mean(blue)

print("Overall brightness:", overall_brightness)
print("Red brightness:", red_brightness)
print("Green brightness:", green_brightness)
print("Blue brightness:", blue_brightness)

"""*Your answer:*

## Thresholding

Convert the image into pure black-and-white using `np.where()`.

### Student Practice
1. Convert the image to grayscale by averaging the 3 channels (`axis=2`).
2. Use `np.where(gray > 128, 255, 0)` to create a binary (black/white) version.
3. Display the result.
4. Try a different threshold (e.g. 100 or 180) and observe how it changes the result.
"""

# Write your thresholding code here

import numpy as np
import matplotlib.pyplot as plt

# 1. Convert RGB image to grayscale
gray = np.mean(img_array, axis=2)

# 2. Convert to black and white using threshold 128
binary = np.where(gray > 128, 255, 0)

# 3. Display the result
plt.imshow(binary, cmap="gray")
plt.axis("off")
plt.show()

"""# Mini Project: Image Analyzer

Write a single program (you can reuse code from above) that prints/displays all of the following for your uploaded image, in order:

1. Image height, width, and number of channels
2. Average brightness (overall, and per channel)
3. The cropped center region
4. Both flipped versions (vertical and horizontal)
5. All 3 RGB channels shown separately
6. The thresholded (black/white) version

### Self-check before you submit
- [ ] I wrote the code myself rather than only uncommenting given code
- [ ] I can explain what every line does, not just that it runs
- [ ] My image display uses `plt.axis("off")` and looks correct
- [ ] I answered all reflection questions in my own words

## Reflection Questions

1. Why is NumPy faster than Python lists? (Refer back to your Part 1 answer — refine it if needed.)

2. Explain broadcasting with an example of your own.

3. What does image shape `(512,512,3)` represent?

4. Why should we avoid printing complete image arrays?

5. Explain RGB channels.

6. Where might you use this exact image-array workflow in a real machine learning project (e.g. what comes right before feeding an image into a CNN)?


from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# --------------------------------------------------
# 1. LOAD IMAGE
# --------------------------------------------------

image_filename = "your_image.jpg"   # Change this to your uploaded image name

img = Image.open(image_filename)
img_array = np.array(img)

# Get image dimensions
height, width, channels = img_array.shape

print("1. IMAGE INFORMATION")
print("Height:", height)
print("Width:", width)
print("Channels:", channels)


# --------------------------------------------------
# 2. AVERAGE BRIGHTNESS
# --------------------------------------------------

red = img_array[:, :, 0]
green = img_array[:, :, 1]
blue = img_array[:, :, 2]

overall_brightness = np.mean(img_array)
red_brightness = np.mean(red)
green_brightness = np.mean(green)
blue_brightness = np.mean(blue)

print("\n2. BRIGHTNESS")
print("Overall brightness:", overall_brightness)
print("Red brightness:", red_brightness)
print("Green brightness:", green_brightness)
print("Blue brightness:", blue_brightness)


# --------------------------------------------------
# 3. CENTER CROP (200 x 200)
# --------------------------------------------------

start_y = (height - 200) // 2
start_x = (width - 200) // 2

crop = img_array[start_y:start_y + 200,
                 start_x:start_x + 200]

plt.figure()
plt.imshow(crop)
plt.title("3. Center Crop")
plt.axis("off")
plt.show()


# --------------------------------------------------
# 4. IMAGE FLIPPING
# --------------------------------------------------

vertical_flip = img_array[::-1, :]
horizontal_flip = img_array[:, ::-1]

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

axes[0].imshow(vertical_flip)
axes[0].set_title("Vertical Flip")
axes[0].axis("off")

axes[1].imshow(horizontal_flip)
axes[1].set_title("Horizontal Flip")
axes[1].axis("off")

plt.show()


# --------------------------------------------------
# 5. RGB CHANNELS
# --------------------------------------------------

fig, axes = plt.subplots(1, 3, figsize=(12, 4))

axes[0].imshow(red, cmap="gray")
axes[0].set_title("Red Channel")
axes[0].axis("off")

axes[1].imshow(green, cmap="gray")
axes[1].set_title("Green Channel")
axes[1].axis("off")

axes[2].imshow(blue, cmap="gray")
axes[2].set_title("Blue Channel")
axes[2].axis("off")

plt.show()


# --------------------------------------------------
# 6. THRESHOLDING
# --------------------------------------------------

# Convert RGB to grayscale
gray = np.mean(img_array, axis=2)

# Convert to black and white
binary = np.where(gray > 128, 255, 0)

plt.figure()
plt.imshow(binary, cmap="gray")
plt.title("6. Thresholded Image")
plt.axis("off")
plt.show()

# Part 15: Text Analysis Using NumPy (NLP Track)

## Why this matters for ML/NLP

Before any NLP model (sentiment classifier, spam detector, chatbot) can process text, the text must be converted into numbers — this is called **vectorization**. NumPy arrays are the underlying data structure for almost every text representation: word counts, one-hot vectors, TF-IDF vectors, and even word embeddings are all just NumPy (or NumPy-like) arrays.

In this section, you'll build a small text analysis pipeline entirely with NumPy — no external NLP libraries — so you understand what's actually happening under the hood before you use libraries like `scikit-learn` or `nltk` later in the course.

## Step 1: From Text to Tokens

The first step in any NLP pipeline is **tokenization** — splitting text into individual words.

### Demonstration
"""

sentence = "NumPy makes numerical computing fast and NumPy makes arrays powerful"

import numpy as np
# Basic tokenization: lowercase + split on spaces
tokens = sentence.lower().split()
print(tokens)

"""### Student Practice

Tokenize this sentence the same way: `"Data Science and Machine Learning use NumPy arrays every single day"`. Store the result in a variable called `tokens2`.

"""

# Write your answer here

import numpy as np
sentence ="Data Science and Machine Learning use NumPy arrays every single day"
token2=sentence.lower().split()
print(token2)

"""## Step 2: Building a Vocabulary

A **vocabulary** is the set of all unique words across your text(s). We'll use `np.unique()` — the same function idea you used earlier for arrays of numbers, now applied to an array of words.

"""

tokens_array = np.array(tokens)
vocabulary = np.unique(tokens_array)
print("Vocabulary:", vocabulary)
print("Vocabulary size:", len(vocabulary))

"""### Student Practice

Build the vocabulary for `tokens2` from Step 1. How many unique words does it contain?

"""

# Write your answer here
import numpy as np
sentence ="Data Science and Machine Learning use NumPy arrays every single day"
token2=sentence.lower().split()
print(token2)
a=np.unique(token2)
print(a)

"""## Step 3: Word Frequency Vector (Bag-of-Words)

A **bag-of-words** vector represents a sentence as an array of word counts, one count per vocabulary word — this ignores word order but captures *what* words appear and *how often*.

### Demonstration: build a word-count vector by hand using NumPy

"""

def bag_of_words_vector(tokens, vocabulary):
    # For each word in the vocabulary, count how many times it appears in tokens
    vector = np.array([np.sum(np.array(tokens) == word) for word in vocabulary])
    return vector

vec = bag_of_words_vector(tokens, vocabulary)
print(vocabulary)
print(vec)

"""### Student Practice — predict then check

Before running, predict: which word(s) will have a count of 2 in the vector above? (Hint: look back at the original sentence — which word repeats?)

*Your prediction:*

Now build the bag-of-words vector for `tokens2` using its own vocabulary, and check your prediction concept applies the same way.


import numpy as np

tokens2 = ["I", "like", "Python", "and", "I", "like", "Python"]

vocab2 = ["I", "like", "Python", "and"]

vector2 = np.array([
    tokens2.count(word) for word in vocab2
])

print("Vocabulary:", vocab2)
print("Vector:", vector2)

"""

# Write your answer here

import numpy as np

tokens2 = ["I", "like", "Python", "and", "I", "like", "Python"]

vocab2 = ["I", "like", "Python", "and"]

vector2 = np.array([
    tokens2.count(word) for word in vocab2
])

print("Vocabulary:", vocab2)
print("Vector:", vector2)

"""## Step 4: Comparing Two Sentences (Cosine Similarity)

Once text is turned into number vectors, we can measure how *similar* two sentences are using **cosine similarity** — a formula you'll see constantly in NLP and recommendation systems:

$$\text{cosine similarity} = \frac{A \cdot B}{\|A\| \times \|B\|}$$

This measures the angle between two vectors, not their length — so it works even if one sentence is longer than another.

### Demonstration

"""

sentence_a = "machine learning uses numpy arrays"
sentence_b = "deep learning also uses numpy arrays heavily"

tokens_a = sentence_a.lower().split()
tokens_b = sentence_b.lower().split()

# Build a shared vocabulary from both sentences combined
combined_vocab = np.unique(np.array(tokens_a + tokens_b))

vec_a = bag_of_words_vector(tokens_a, combined_vocab)
vec_b = bag_of_words_vector(tokens_b, combined_vocab)

print("Vector A:", vec_a)
print("Vector B:", vec_b)

# Cosine similarity using NumPy dot product and norm
cosine_sim = np.dot(vec_a, vec_b) / (np.linalg.norm(vec_a) * np.linalg.norm(vec_b))
print("Cosine similarity:", cosine_sim)

"""### Student Practice

Pick two sentences of your own (write them below) — one pair that should be *similar* in meaning/topic, and one pair that should be *very different*. Compute the cosine similarity for both pairs and confirm your intuition matches the numbers.

"""

# Write your answer here

import numpy as np

def cosine_similarity(A, B):
    return np.dot(A, B) / (np.linalg.norm(A) * np.linalg.norm(B))


# Pair 1 - Similar sentences
sentence1 = "I like playing cricket"
sentence2 = "I enjoy playing cricket"

vocab1 = ["I", "like", "playing", "cricket", "enjoy"]

A = np.array([sentence1.split().count(word) for word in vocab1])
B = np.array([sentence2.split().count(word) for word in vocab1])

similarity1 = cosine_similarity(A, B)

print("Pair 1:")
print("Vector 1:", A)
print("Vector 2:", B)
print("Cosine Similarity:", similarity1)


# Pair 2 - Very different sentences
sentence3 = "I like playing cricket"
sentence4 = "The computer is very fast"

vocab2 = ["I", "like", "playing", "cricket",
          "The", "computer", "is", "very", "fast"]

C = np.array([sentence3.split().count(word) for word in vocab2])
D = np.array([sentence4.split().count(word) for word in vocab2])

similarity2 = cosine_similarity(C, D)

print("\nPair 2:")
print("Vector 1:", C)
print("Vector 2:", D)
print("Cosine Similarity:", similarity2)

"""**Reflection:** In your own words, why does cosine similarity give a value close to 1 for similar sentences and close to 0 for unrelated sentences? What would a `cosine similarity` of exactly 1 mean about two vectors?

*Your answer:* **Your answer:**

Cosine similarity is close to 1 when two sentences have similar word patterns and point in a similar direction. It is close to 0 when they have very few or no words in common.

A cosine similarity of exactly 1 means the two vectors point in the same direction, so they have the same pattern of word frequencies (even if their sizes are different).

## Step 5: Most Frequent Words

### Student Practice

Take any paragraph of your choice (3-4 sentences, write it below as a string). Then:
1. Tokenize it.
2. Build its vocabulary and word-count vector (reuse `bag_of_words_vector`).
3. Use NumPy to find and print the **top 3 most frequent words** (hint: look at sorting — `np.argsort()` sorts indices by value, and slicing with `[::-1]` reverses order).

import numpy as np

# Paragraph
text = '''
Python is easy to learn.
Python is useful for data analysis.
I like Python because Python is simple.
'''

# 1. Tokenize
tokens = text.lower().split()

# 2. Build vocabulary
vocabulary = list(set(tokens))

# Build word-count vector
counts = np.array([tokens.count(word) for word in vocabulary])

# 3. Find top 3 most frequent words
sorted_indices = np.argsort(counts)[::-1]

top_3 = sorted_indices[:3]

print("Top 3 most frequent words:")

for i in top_3:
    print(vocabulary[i], ":", counts[i])
"""

# Write your answer here


import numpy as np

# Paragraph
text = """
Python is easy to learn.
Python is useful for data analysis.
I like Python because Python is simple.
"""

# 1. Tokenize
tokens = text.lower().split()

# 2. Build vocabulary
vocabulary = list(set(tokens))

# Build word-count vector
counts = np.array([tokens.count(word) for word in vocabulary])

# 3. Find top 3 most frequent words
sorted_indices = np.argsort(counts)[::-1]

top_3 = sorted_indices[:3]

print("Top 3 most frequent words:")

for i in top_3:
    print(vocabulary[i], ":", counts[i])

"""# Mini Project: Simple Text Similarity Checker (NLP Track)

Build a small program that:

1. Takes **three** short sentences of your choice (write them as strings).
2. Tokenizes all three and builds one shared vocabulary across all of them.
3. Converts each sentence into a bag-of-words vector using that shared vocabulary.
4. Computes cosine similarity between every pair of sentences (3 pairs total: 1-2, 1-3, 2-3).
5. Prints which two sentences are the **most similar** to each other, based on the highest cosine similarity score.

### Self-check before you submit
- [ ] I wrote my own three sentences (not copied from the notebook)
- [ ] I can explain what a bag-of-words vector represents, in my own words
- [ ] I can explain why cosine similarity works even when sentences are different lengths
- [ ] My program correctly identifies and prints the most similar pair

## Reflection Questions (NLP Track)

1. Why do we need to convert text into numbers before a machine learning model can use it?

2. What information does a bag-of-words vector *lose* about the original sentence? (Hint: think about what `split()` and counting alone doesn't capture.)

3. Why might cosine similarity be a better similarity measure than simply comparing raw word-count differences?

4. Name one real-world application that likely uses something like this text-vectorization + similarity approach (e.g. search engines, plagiarism checkers, recommendation systems — pick one and explain briefly).





Here is a **complete, simple student-style solution** you can use.

# Mini Project: Simple Text Similarity Checker

```python
import numpy as np

# 1. Three sentences of my choice
sentence1 = "I like playing cricket"
sentence2 = "I enjoy playing cricket"
sentence3 = "I like eating pizza"

# 2. Tokenize all three sentences
tokens1 = sentence1.lower().split()
tokens2 = sentence2.lower().split()
tokens3 = sentence3.lower().split()

# Create one shared vocabulary
all_words = tokens1 + tokens2 + tokens3
vocabulary = list(dict.fromkeys(all_words))

print("Vocabulary:", vocabulary)


# 3. Function to create Bag-of-Words vector
def bag_of_words_vector(tokens, vocabulary):
    return np.array([tokens.count(word) for word in vocabulary])


A = bag_of_words_vector(tokens1, vocabulary)
B = bag_of_words_vector(tokens2, vocabulary)
C = bag_of_words_vector(tokens3, vocabulary)

print("Vector 1:", A)
print("Vector 2:", B)
print("Vector 3:", C)


# 4. Cosine similarity function
def cosine_similarity(A, B):
    return np.dot(A, B) / (np.linalg.norm(A) * np.linalg.norm(B))


similarity_12 = cosine_similarity(A, B)
similarity_13 = cosine_similarity(A, C)
similarity_23 = cosine_similarity(B, C)

print("\nCosine Similarities:")
print("Sentence 1 & 2:", similarity_12)
print("Sentence 1 & 3:", similarity_13)
print("Sentence 2 & 3:", similarity_23)


# 5. Find the most similar pair
similarities = {
    "Sentence 1 & 2": similarity_12,
    "Sentence 1 & 3": similarity_13,
    "Sentence 2 & 3": similarity_23
}

most_similar = max(similarities, key=similarities.get)

print("\nMost similar pair:", most_similar)
print("Similarity score:", similarities[most_similar])
```

### Expected result

The most similar pair should be:

```text
Sentence 1 & 2
```

because both contain:

```text
playing
cricket
```

---

# Reflection Questions

### 1. Why do we convert text into numbers?

Machine-learning models work with **numerical data**, not ordinary words. Converting text into numbers allows the model to perform mathematical operations and learn patterns.

---

### 2. What information does Bag-of-Words lose?

Bag-of-Words loses the **order of words** and the sentence structure.

For example:

```text
"I like Python"
"Python like I"
```

would have the same word counts even though their word order is different.

---

### 3. Why is cosine similarity better than raw word-count differences?

Cosine similarity compares the **direction/pattern of the vectors**, rather than just their size. This makes it useful when sentences have different lengths but contain similar words.

---

### 4. Real-world application

**Search engines** can use text vectorization and similarity to compare a user's search query with documents. Documents whose vectors are more similar to the query can be ranked higher in the search results.


"""